config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  namespace :admin do
    resources :ordered_items, only: [:update]
  end
  root to: "public/homes#top"

  #顧客用
  #URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }

  namespace :public do
    resources :customers, only: [:show, :edit, :upadate]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'conplete'
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    #退会確認画面
    get 'customers/:id/out_check' => 'customers#out_check', as: 'out_check'
    #論理削除用のルーティング
    patch 'customers/:id' => 'customers#out', as: 'out'
  end




  #管理者用
  #URL /admin/sign_in
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  get 'admin' => 'admin/homes#top'
  namespace :admin do
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  description :text
#  name        :string
#  price       :integer
#  sale_status :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  genre_id    :integer
#
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordered_items, dependent: :destroy

  has_one_attached :item_image


  def get_item_image
    if item_image.attached?
      item_image
    else
      'no_image.jpg'
    end
  end

  def tax
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def update
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :name, :description, :price, :sale_status)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h1>Admin::Items#edit</h1>
<p>Find me in app/views/admin/items/edit.html.erb</p>

app/views/admin/items/index.html.erb
<h1>Admin::Items#index</h1>
<p>Find me in app/views/admin/items/index.html.erb</p>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>

<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
  <h3>商品画像</h3>
    <%= f.file_field :item_image, accept: "image/*" %>
  <h3>商品名</h3>
    <%= f.text_field :name %>
  <h3>商品説明</h3>
    <%= f.text_area :description %>
  <h3>税抜き価格</h3>
    <%= f.text_field :price %>円
  <h3>販売ステータス</h3>
    <%= f.radio_button :sale_status, :true %>
    <%= f.label :sale_status, "販売中", :value => true %>
    <%= f.radio_button :sale_status, :false %>
    <%= f.label :sale_status, "販売停止中", :value => false %>
  <%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>

<%= image_tag @item.get_item_image, size: "100x100" %>
<p><%= @item.name %></p>
<p><%= @item.price %>円</p>
<% if @item.sale_status == true %>
  <p>販売中</p>
<% else %>
  <p>販売停止中</p>
<% end %>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>