config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  namespace :admin do
    resources :ordered_items, only: [:update]
  end
  root to: "public/homes#top"

  #顧客用
  #URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }

  namespace :public do
    resources :customers, only: [:show, :edit, :upadate]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'conplete'
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    #退会確認画面
    get 'customers/:id/out_check' => 'customers#out_check', as: 'out_check'
    #論理削除用のルーティング
    patch 'customers/:id' => 'customers#out', as: 'out'
  end




  #管理者用
  #URL /admin/sign_in
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  get 'admin' => 'admin/homes#top'
  namespace :admin do
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <li><%= link_to "管理者のlog inへ", new_admin_session_path %></li>
      <li><%= link_to "商品登録画面", new_admin_item_path %></li>
      <% if customer_signed_in? %>
        <li><%= link_to "顧客の詳細画面", public_customer_path(current_customer) %></li>
        <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
        <li><%= link_to "カートへ", public_cart_items_path %></li>
        <li><%= link_to "商品一覧", public_items_path %></li>
        <li><%= link_to "注文履歴一覧", public_orders_path %></li>
        <li><%= link_to "管理者のtop", admin_path %></li>
      <% else %>
        <li><%= link_to "新規登録", new_customer_registration_path %></li>
        <li><%= link_to "ログイン", new_customer_session_path %></li>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>